[package]
name = "rust"
version = "0.1.0"
authors = ["Filip Wachowiak <filipw01@interia.eu>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.10.5"
nannou = "0.18.1"
nannou_egui = "0.5.0"
